version: "3.7"

services:
  db:
    restart: unless-stopped
    image: postgres
    env_file:
      - .env
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    networks:
      - server_default
  redis:
    restart: unless-stopped
    image: redis
    command: redis-server
    ports:
      - "6379:6379"
    networks:
      - server_default
  django_daphne:
    restart: unless-stopped
    volumes:
      - ./backend:/backend
      - static:/backend/static/
    env_file:
      - .env
    build:
      context: ./backend
    ports:
      - "8000:8000"
    depends_on:
      - db
      - redis
    networks:
      - server_default
  nginx_casinoa:
    restart: unless-stopped
    volumes:
      - static:/backend/static/
    build: ./nginx-node
    ports:
      - "81:81"
    depends_on:
      - frontend_casinoa
    networks:
      - server_default
  frontend_casinoa:
    restart: unless-stopped
    build: ./frontend
    env_file:
      - .env
    volumes:
      - ./frontend:/frontend
      - node_modules:/frontend/node_modules/
    ports:
      - "3030:3000"
    depends_on:
      - django_daphne
    networks:
      - server_default


volumes:
  node_modules:
  static:
  postgres_data:
networks:
  server_default:
    external: true
